apiVersion: v1
kind: Service
metadata:
  name: {{ include "provider-service.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 28442
      targetPort: 28442
      protocol: TCP
      name: http
    - port: 8442
      targetPort: 8442
      protocol: TCP
      name: gateway
