name: package

on:
  push:
    branches:
      - feat/publish
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.1 # Also update in lint-and-test.yaml
      - name: Packeges
        run: |
          mkdir -p public 
          cd public
          helm package ../charts/*
          helm repo index .
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public